apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: test-app-iuwj
    appstudio.openshift.io/component: build-suite-test-component-image-url-tsts
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: build-suite-test-component-image-url-tsts
  namespace: build-e2e-specific-image-url-jjoa
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: build-suite-test-component-image-url-tsts
status:
  configuration:
    generatedName: ""
